### ISSUE TITLE
Release npm as JS instead of coffeescript

### ISSUE THREAD

**Issue by warrenrumak** [joscha/gulp-rewrite-css#12]
Can't say that I'm super-happy at the idea of being forced to download a large dependency like coffeescript to subsequently compile ~100 lines of CS into ~100 lines of JS, once, for a simple operation such as rewriting the contents of a file.  Out of consideration for users of this library, it would be better to publish the npm package as JS instead.

**Comment by joscha** [comment]
@warrenrumak you have a point :) could you provide a PR? I'd be happy to merge it and release a new version then.

**Comment by warrenrumak** [comment]
Not sure if I can do that with confidence as I would not be able to test publishing your package to npm. :-)
But shortly, all you should have to do is use 'prepublish' in package.config instead of a 'postinstall', and move coffeescript into devDependencies.

Further guidance in the npm docs, they mention coffeescript specifically:
https://docs.npmjs.com/misc/scripts

**Comment by joscha** [comment]
@warrenrumak can you try if `gulp-rewrite-css@0.0.5-beta` works for you?

**Comment by joscha** [comment]
@warrenrumak did you find time to check it, yet?

**Comment by banbanchs** [comment]
@joscha Hi, `gulp-rewrite-css@0.0.5-beta` not work for me. I guess you need to upload `lib/` folder to github like [pow](https://github.com/basecamp/pow).
 :)

**Comment by joscha** [comment]
@banbanchs could you provide a PR on top of `0.0.5-beta`?

**Comment by banbanchs** [comment]
@joscha sended. #16

**Comment by joscha** [comment]
@banbanchs released as `0.0.5`.
