### ISSUE TITLE
gulp.utils object returned when debug enabled

### ISSUE THREAD

**Issue by lennynyktyk** [joscha/gulp-rewrite-css#33]
When I enable the `debug` option and have a URL which is relative and is relative to the base, https://github.com/joscha/gulp-rewrite-css/blob/master/src/index.coffee#L72, causes mungePath to return a `gulp.utils` object instead of `null`.  I think an explicit `null` just needs to be inserted after that.

**Comment by joscha** [comment]
good find! Would you mind opening a PR for that and possibly a test for it?

**Comment by lennynyktyk** [comment]
I'm sorry I'm don't have enough free time to setup a PR.

**Comment by joscha** [comment]
Ok. Could you attach the CSS that causes the problem to this issue?

**Comment by yourimiyi** [comment]
before:
`line 83 : return gutil.log(magenta(PLUGIN_NAME), 'not rewriting absolute path for', magenta(match), 'in', magenta(sourceFilePath));`
to:
`line 83 : return gutil.log(magenta(PLUGIN_NAME), 'not rewriting absolute path for', magenta(match), 'in', magenta(sourceFilePath)), undefined;`

just add ',' with undefined or null.

**Comment by yourimiyi** [comment]
mungePath should return String or undefined(for abs-url, invalid targetUrl)

just add '`, undefined`' end of line

`line 83: return gutil.log(magenta(PLUGIN_NAME), 'not rewriting absolute path for', magenta(match), 'in', magenta(sourceFilePath)), undefined;`

or, remove 'return'.
`line 83: gutil.log(magenta(PLUGIN_NAME), 'not rewriting absolute path for', magenta(match), 'in', magenta(sourceFilePath));`

thanks again.

**Comment by joscha** [comment]
`0.0.9` has the fix.
