### ISSUE TITLE
Rewriting for absolute URLs

### ISSUE THREAD

**Issue by danpalmer** [joscha/gulp-rewrite-css#34]
I'm trying to use `gulp-rewrite-css` to transform my paths from `/media/foo.png` to `/media/foo.png?v=123`. I've got a mapping that I can use with `adaptPath`, but gulp-rewrite-css refuses to modify absolute URLs.

What is the reasoning behind not rewriting absolute URLs, and do you think adding an option for this would be a good thing?

**Comment by joscha** [comment]
The reason for not rewriting absolute paths is, that the reference point is clear. There is not really a use-case to rewrite them. If you only need to add a query parameter, why does a simple regular expression search & replace not work for you?

**Comment by danpalmer** [comment]
> why does a simple regular expression search & replace not work for you?

We have a mapping of all our assets to their new paths (which happen to have ?v= params in them for cachebusting). Because of this, a simple regex replace doesn't really work well.

> The reason for not rewriting absolute paths is, that the reference point is clear.

It sounds like this library is specifically for changing URLs when a file is moved in a filesystem, whereas we're trying to use it to rewrite URLs in a more generic way. Maybe that's the issue? If so, maybe this library just doesn't fit our use-case?

**Comment by joscha** [comment]
@danpalmer I see - and yes, to the second point. However I think it should be fairly easy to adapt the code to also process absolute URLs. If you can make the change so it is optional and write a few tests for it we might even be able to merge it in - have you had a look at [postcss](https://www.npmjs.com/package/postcss)?

**Comment by stof** [comment]
@danpalmer you may want to look at https://github.com/sindresorhus/gulp-rev
