### ISSUE TITLE
Are there any working demo's you can provide? 

### ISSUE THREAD

**Issue by gward35** [joscha/gulp-rewrite-css#77]
I'm wondering if this tool is right for my needs. I tried to create a similar task using replace. I'm not sure based on your usage example where or how I would define the new url. Please see my attempt (which doesnt work) 

var config = require('../config');
if (!config.tasks.js) return;

var gulp = require('gulp');
var replace = require('gulp-replace');

var fontURL = function () {
	return gulp.src('../site/fractal/components/preview/fonts.css')
	.pipe(replace('/assets/fonts/', './'))
	.pipe(gulp.dest('../site/fractal/components/preview/fonts.css'));
}

gulp.task('font:url', ['fractal'], fontURL);
module.exports = fontURL

**Comment by joscha** [comment]
@gward35 you can have a look at the tests to see the module in action with all the different options.
