### ISSUE TITLE
Replace "\" to "/" in target url

### ISSUE THREAD

**Issue by lswierzewski** [joscha/gulp-rewrite-css#9]
Replace line *51* in *src/index.coffee* file:

`targetUrl = targetUrl.replace '\\', '/' if path.sep is '\\'`

to

`targetUrl = targetUrl.replace /\\/g, '/' if path.sep is '\\'`

to replace globally all backslashes to slashes in a string, not just the first occurance.

**Comment by joscha** [comment]
closed via 84e8422744010c528424409bbaccca9a32fddf5c
